name: dbf
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - asn1crypto=1.3.0=py37_0
  - ca-certificates=2020.1.1=0
  - certifi=2020.4.5.1=py37_0
  - cffi=1.14.0=py37h2e261b9_0
  - chardet=3.0.4=py37_1003
  - click=7.1.1=py_0
  - cryptography=2.8=py37h1ba5d50_0
  - flask=1.1.2=py_0
  - idna=2.9=py_1
  - itsdangerous=1.1.0=py37_0
  - jinja2=2.11.1=py_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libblas=3.8.0=14_openblas
  - libcblas=3.8.0=14_openblas
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_5
  - liblapack=3.8.0=14_openblas
  - libopenblas=0.3.7=h5ec1e0e_6
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - markupsafe=1.1.1=py37h7b6447c_0
  - ncurses=6.2=he6710b0_0
  - neo4j-python-driver=1.7.6=pyh516909a_0
  - neobolt=1.7.17=py37h8f50634_0
  - neotime=1.7.4=py_0
  - numpy=1.18.1=py37h8960a57_1
  - openssl=1.1.1g=h7b6447c_0
  - pandas=1.0.3=py37h0573a6f_0
  - pika=1.1.0=py_0
  - pip=20.0.2=py37_1
  - pycparser=2.20=py_0
  - pyopenssl=19.1.0=py37_0
  - pysocks=1.7.1=py37_0
  - python=3.7.7=hcf32534_0_cpython
  - python-dateutil=2.8.1=py_0
  - python_abi=3.7=1_cp37m
  - pytz=2019.3=py_0
  - readline=8.0=h7b6447c_0
  - requests=2.23.0=py37_0
  - setuptools=46.1.3=py37_0
  - six=1.14.0=py_1
  - sqlite=3.31.1=h62c20be_1
  - tk=8.6.8=hbc83047_0
  - tqdm=4.45.0=pyh9f0ad1d_0
  - urllib3=1.25.8=py37_0
  - werkzeug=1.0.1=py_0
  - wheel=0.34.2=py37_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - names==0.3.0
prefix: /home/dtjo223/miniconda3/envs/dbf

